### ISSUE TITLE
Uncaught AssertionError: The expression evaluated to a falsy value:  (0, _assert.default)(dockP...

### ISSUE THREAD

**Issue by AlanAguilarSologuren** [atom-community/atom-ide-debugger#14] opened 2021-02-17 16:21 UTC
[Enter steps to reproduce:]

1. Clean installation of Atom, atom-ide-base, ide-python, atom-ide-debugger and atom-ide-console

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Uncaught AssertionError: The expression evaluated to a falsy value:

  (0, _assert.default)(dockPane.element != null)

```
At assert.js:362

AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(dockPane.element != null)

    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1171250)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1172691)
    at Pane.setFlexScale (/usr/share/atom/resources/app/static/<embedded>:11:454811)
    at Pane.split (/usr/share/atom/resources/app/static/<embedded>:11:466012)
    at Pane.splitDown (/usr/share/atom/resources/app/static/<embedded>:11:465717)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350343)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348818)
    at /packages/atom-ide-debugger/dist/main.js:427:21)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350343)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:667984)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:837590)
    at SelectListView.didClickItem (/usr/share/atom/resources/app/static/<embedded>:11:835532)
    at ListItemView.onclick (/usr/share/atom/resources/app/static/<embedded>:11:834522)
    at ListItemView.didClick (/usr/share/atom/resources/app/static/<embedded>:11:838610)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 2.3.5 
atom-ide-console 0.0.2 
atom-ide-datatip 0.23.4 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.9 
atom-ide-markdown-service 2.0.0 
atom-ide-outline 1.17.0 
atom-ide-signature-help 0.15.2 
busy-signal 2.0.1 
declarations 1.1.3 
file-icons 2.1.46 
ide-python 1.7.3 
intentions 1.1.5 
linter 3.3.0 
linter-ui-default 3.2.5 
minimap 4.39.8 
```

**Comment by aminya** [comment] 2021-03-22 07:04
Duplicate of https://github.com/atom-community/atom-ide-debugger/issues/18

**Closed by aminya** 2021-03-22 07:04 UTC
