### ISSUE TITLE
Failed to activate the atom-ide-debugger package

### ISSUE THREAD

**Issue by haroldosales** [atom-community/atom-ide-debugger#11] opened 2021-01-10 22:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: "Manjaro Linux"
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Failed to activate the atom-ide-debugger package

```
At The expression evaluated to a falsy value:

  (0, _assert.default)(oldElem.constructor.name === 'ReactMountRootElement')


AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(oldElem.constructor.name === 'ReactMountRootElement')

    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:88:23)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:95:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/renderReactRoot.js:10:53)
    at /packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/renderReactRoot.js:40:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/atom-ide-debugger/dist/main.js:54:24)
    at /packages/atom-ide-debugger/dist/main.js:930:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:907:27)
    at Package.activateNow (/usr/lib/atom/src/package.js:231:34)
    at /usr/lib/atom/src/package.js:1058:18
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.triggerDeferredActivationHooks (/usr/lib/atom/src/package-manager.js:824:34)
    at /usr/lib/atom/src/package-manager.js:753:12
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-debugger 0.0.3 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
debug 0.0.1 
emmet 2.4.3 
fox-syntax-theme 1.2.0 
goto-definition 1.3.4 
ide-php 0.7.18 
intentions 1.1.5 
linter 3.2.3 
linter-php 1.6.1 
linter-ui-default 2.4.0 
minima-syntax 0.0.3 
minima-ui 0.0.7 
minimap 4.37.1 
php-debug 0.3.5 
script 3.29.3 
seti-icons 1.5.4 
sync-settings 5.2.0 
terminal-tab 0.6.0 
varone-dark-ui 2.0.0 
```

**Comment by aminya** [comment] 2021-01-10 23:27
Duplicate of #10

**Closed by aminya** 2021-01-10 23:27 UTC
